[package]
name = "spoticord"
version = "2.0.0-pre"
edition = "2021"
rust-version = "1.64.0"

[[bin]]
name = "spoticord"
path = "src/main.rs"

[features]
default = []
metrics = ["lazy_static", "prometheus"]

[dependencies]
dotenv = "0.15.0"
env_logger = "0.10.0"
ipc-channel = { version = "0.16.0", features = ["async"] }
lazy_static = { version = "1.4.0", optional = true }
librespot = { version = "0.4.2", default-features = false }
log = "0.4.17"
prometheus = { version = "0.13.3", optional = true, features = ["push", "process"] }
reqwest = "0.11.14"
samplerate = "0.2.4"
serde = "1.0.152"
serde_json = "1.0.93"
serenity = { version = "0.11.5", features = ["framework", "cache", "standard_framework"], default-features = false }
songbird = "0.3.0"
thiserror = "1.0.38"
time = "0.3.20"
tokio = { version = "1.25.0", features = ["rt", "full"] }
zerocopy = "0.6.1"
