[package]
name = "spoticord"
version = "2.0.0-beta"
edition = "2021"

[[bin]]
name = "spoticord"
path = "src/main.rs"

[dependencies]
chrono = "0.4.22"
dotenv = "0.15.0"
env_logger = "0.9.3"
ipc-channel = { version = "0.16.0", features = ["async"] }
librespot = { version = "0.4.2",  default-features = false }
log = "0.4.17"
redis = "0.22.1"
reqwest = "0.11.12"
samplerate = "0.2.4"
serde = "1.0.147"
serde_json = "1.0.87"
serenity = { version = "0.11.5", features = ["voice"] }
songbird = "0.3.0"
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = ["rt", "full"] }
zerocopy = "0.6.1"
