[package]
name = "spoticord"
version = "2.0.0-beta"
edition = "2021"

[[bin]]
name = "spoticord"
path = "src/main.rs"

[profile.release]
lto = true
codegen-units = 1
strip = true
opt-level = "z"
panic = "abort"

[dependencies]
chrono = "0.4.22"
dotenv = "0.15.0"
env_logger = "0.9.0"
ipc-channel = { version = "0.16.0", features = ["async"] }
librespot = { version = "0.4.2",  default-features = false }
log = "0.4.17"
redis = "0.22.1"
reqwest = "0.11.11"
samplerate = "0.2.4"
serde = "1.0.144"
serde_json = "1.0.85"
serenity = { version = "0.11.5", features = ["voice"] }
songbird = "0.3.0"
thiserror = "1.0.33"
tokio = { version = "1.20.1", features = ["rt", "full"] }
zerocopy = "0.6.1"
