[package]
name = "spoticord"
version = "2.1.0"
edition = "2021"
rust-version = "1.65.0"

[[bin]]
name = "spoticord"
path = "src/main.rs"

[dependencies]
dotenv = "0.15.0"
env_logger = "0.10.0"
lazy_static = { version = "1.4.0", optional = true }
librespot = { version = "0.4.2", default-features = false }
log = "0.4.17"
reqwest = "0.11.18"
samplerate = "0.2.4"
serde = "1.0.163"
serde_json = "1.0.96"
serenity = { version = "0.11.5", features = ["framework", "cache", "standard_framework"], default-features = false }
songbird = "0.3.2"
thiserror = "1.0.40"
time = "0.3.21"
tokio = { version = "1.28.1", features = ["rt", "full"] }
zerocopy = "0.6.1"
