[package]
name = "spoticord"
version = "2.1.0"
edition = "2021"
rust-version = "1.65.0"

[[bin]]
name = "spoticord"
path = "src/main.rs"

[features]
stats = ["redis"]

[dependencies]
anyhow = "1.0.75"
dotenv = "0.15.0"
env_logger = "0.10.0"
hex = "0.4.3"
librespot = { version = "0.4.2", default-features = false }
log = "0.4.20"
protobuf = "2.28.0"
redis = { version = "0.23.3", optional = true }
reqwest = "0.11.20"
samplerate = "0.2.4"
serde = "1.0.188"
serde_json = "1.0.107"
serenity = { version = "0.11.6", features = ["framework", "cache", "standard_framework"], default-features = false }
songbird = "0.3.2"
thiserror = "1.0.48"
time = "0.3.28"
tokio = { version = "1.32.0", features = ["rt", "full"] }
zerocopy = "0.7.5"

[profile.release]
opt-level = 3
lto = true
