[package]
name = "spoticord_config"
version = "2.2.4"
edition = "2021"

[dependencies]
rspotify = { version = "0.13.2", default-features = false, features = [
    "client-reqwest",
    "reqwest-rustls-tls",
] }
serenity = "0.12.2"
