[registries.crates-io]
protocol = "sparse"

[target.x86_64-pc-windows-gnu]
rustflags = "-C link-args=-lssp" # Does not compile without this line

[target.aarch64-unknown-linux-gnu]
rustflags = "-C linker=aarch64-linux-gnu-gcc"